"""Local stand-in for Perenual, used when MOCK_PERENUAL=true (see config.py).

Records are shaped exactly like a real `/species/details/{id}` response (the
richest shape Perenual returns — see normalize_plant() in perenual_client.py),
built from field names and formats confirmed against real API responses
during development: sunlight is space-separated and inconsistently cased,
dimensions is a list, flowering_season is usually null, etc. This lets the
whole filter/normalize pipeline run unmodified against realistic data with
zero API calls, for local UI development and testing.

Image URLs are intentionally blank — Perenual's image URLs are short-lived
signed S3 links, not worth faking here. Expect broken image icons in mock
mode; that's expected, not a bug.
"""

from __future__ import annotations

MOCK_SPECIES: list[dict] = [
    {
        "id": 1,
        "common_name": "European Silver Fir",
        "scientific_name": ["Abies alba"],
        "description": "A tall, narrow conifer often grown as a windbreak or Christmas tree.",
        "dimensions": [{"type": "Height", "min_value": 60, "max_value": 60, "unit": "feet"}],
        "cycle": "Perennial",
        "hardiness": {"min": "7", "max": "7"},
        "watering": "Frequent",
        "sunlight": ["full sun"],
        "soil": [],
        "flowers": False,
        "flowering_season": None,
        "edible_fruit": False,
        "edible_leaf": False,
        "default_image": {},
    },
    {
        "id": 2,
        "common_name": "purple coneflower",
        "scientific_name": ["Echinacea purpurea"],
        "description": "Prairie native with rosy-purple daisy-like blooms, popular with pollinators.",
        "dimensions": [{"type": "Height", "min_value": 2, "max_value": 4, "unit": "feet"}],
        "cycle": "Perennial",
        "hardiness": {"min": "3", "max": "9"},
        "watering": "Average",
        "sunlight": ["full sun"],
        "soil": ["Loamy", " Clay "],
        "flowers": True,
        "flowering_season": "Summer",
        "edible_fruit": False,
        "edible_leaf": False,
        "default_image": {},
    },
    {
        "id": 3,
        "common_name": "Blueberry Bush",
        "scientific_name": ["Vaccinium corymbosum"],
        "description": "Deciduous shrub grown for its edible berries and fall foliage color.",
        "dimensions": [{"type": "Height", "min_value": 6, "max_value": 12, "unit": "feet"}],
        "cycle": "Perennial",
        "hardiness": {"min": "3", "max": "7"},
        "watering": "Average",
        "sunlight": ["Full sun"],
        "soil": ["Acidic", " Well-drained"],
        "flowers": True,
        "flowering_season": "Spring",
        "edible_fruit": True,
        "edible_leaf": False,
        "default_image": {},
    },
    {
        "id": 4,
        "common_name": "hosta",
        "scientific_name": ["Hosta sieboldiana"],
        "description": "Shade-loving perennial grown for its large, textured foliage.",
        "dimensions": [],
        "cycle": "Perennial",
        "hardiness": {"min": "3", "max": "8"},
        "watering": "Average",
        "sunlight": ["full shade"],
        "soil": ["Loamy"],
        "flowers": True,
        "flowering_season": "Summer",
        "edible_fruit": False,
        "edible_leaf": False,
        "default_image": {},
    },
    {
        "id": 5,
        "common_name": "Sweet Basil",
        "scientific_name": ["Ocimum basilicum"],
        "description": "Tender culinary herb, usually grown as an annual outside the tropics.",
        "dimensions": [{"type": "Height", "min_value": 1, "max_value": 2, "unit": "feet"}],
        "cycle": "Annual",
        "hardiness": {"min": "10", "max": "11"},
        "watering": "Frequent",
        "sunlight": ["full sun"],
        "soil": [],
        "flowers": True,
        "flowering_season": None,
        "edible_fruit": False,
        "edible_leaf": True,
        "default_image": {},
    },
    {
        "id": 6,
        "common_name": "Christmas Fern",
        "scientific_name": ["Polystichum acrostichoides"],
        "description": "Evergreen woodland fern, tolerant of deep shade and dry soil.",
        "dimensions": [{"type": "Height", "min_value": 1, "max_value": 2, "unit": "feet"}],
        "cycle": "Perennial",
        "hardiness": {"min": "4", "max": "9"},
        "watering": "Average",
        "sunlight": ["filtered shade"],
        "soil": [],
        "flowers": False,
        "flowering_season": None,
        "edible_fruit": False,
        "edible_leaf": False,
        "default_image": {},
    },
    {
        "id": 7,
        "common_name": "Serviceberry",
        "scientific_name": ["Amelanchier canadensis"],
        "description": "Multi-season native: spring flowers, edible summer berries, fall color.",
        "dimensions": [{"type": "Height", "min_value": 6, "max_value": 20, "unit": "feet"}],
        "cycle": "Perennial",
        "hardiness": {"min": "3", "max": "8"},
        "watering": "Average",
        "sunlight": ["part shade"],
        "soil": ["Loamy", "Sandy"],
        "flowers": True,
        "flowering_season": "Spring",
        "edible_fruit": True,
        "edible_leaf": False,
        "default_image": {},
    },
    {
        "id": 8,
        "common_name": "English Lavender",
        "scientific_name": ["Lavandula angustifolia"],
        "description": "Fragrant, drought-tolerant perennial with culinary and ornamental uses.",
        "dimensions": [{"type": "Height", "min_value": 1, "max_value": 3, "unit": "feet"}],
        "cycle": "Perennial",
        "hardiness": {"min": "5", "max": "9"},
        "watering": "Minimum",
        "sunlight": ["Full sun"],
        "soil": ["Sandy", " Well-drained "],
        "flowers": True,
        "flowering_season": "Summer",
        "edible_fruit": False,
        "edible_leaf": True,
        "default_image": {},
    },
    {
        "id": 9,
        "common_name": "Japanese Maple",
        "scientific_name": ["Acer palmatum"],
        "description": "Ornamental small tree prized for delicate, colorful foliage.",
        "dimensions": [{"type": "Height", "min_value": 10, "max_value": 25, "unit": "feet"}],
        "cycle": "Perennial",
        "hardiness": {"min": "5", "max": "8"},
        "watering": "Average",
        "sunlight": ["filtered shade"],
        "soil": [],
        "flowers": False,
        "flowering_season": None,
        "edible_fruit": False,
        "edible_leaf": False,
        "default_image": {},
    },
    {
        "id": 10,
        "common_name": "tomato",
        "scientific_name": ["Solanum lycopersicum"],
        "description": "Warm-season vegetable garden staple, grown as an annual.",
        "dimensions": [{"type": "Height", "min_value": 3, "max_value": 6, "unit": "feet"}],
        "cycle": "Annual",
        "hardiness": {"min": "10", "max": "11"},
        "watering": "Frequent",
        "sunlight": ["full sun"],
        "soil": ["Loamy", "Well-drained"],
        "flowers": True,
        "flowering_season": "Summer",
        "edible_fruit": True,
        "edible_leaf": False,
        "default_image": {},
    },
    {
        "id": 11,
        "common_name": "Boxwood",
        "scientific_name": ["Buxus sempervirens"],
        "description": "Classic dense evergreen shrub, often clipped into hedges.",
        "dimensions": [{"type": "Height", "min_value": 3, "max_value": 6, "unit": "feet"}],
        "cycle": "Perennial",
        "hardiness": {"min": "5", "max": "9"},
        "watering": "Average",
        "sunlight": ["part shade"],
        "soil": [],
        "flowers": False,
        "flowering_season": None,
        "edible_fruit": False,
        "edible_leaf": False,
        "default_image": {},
    },
    {
        "id": 12,
        "common_name": "black-eyed susan",
        "scientific_name": ["Rudbeckia hirta"],
        "description": "Cheerful, tough native wildflower blooming from midsummer into fall.",
        "dimensions": [{"type": "Height", "min_value": 1, "max_value": 3, "unit": "feet"}],
        "cycle": "Perennial",
        "hardiness": {"min": "3", "max": "9"},
        "watering": "Average",
        "sunlight": ["full sun"],
        "soil": [],
        "flowers": True,
        "flowering_season": "Summer to Fall",
        "edible_fruit": False,
        "edible_leaf": False,
        "default_image": {},
    },
    {
        "id": 13,
        "common_name": "Peppermint",
        "scientific_name": ["Mentha piperita"],
        "description": "Vigorous, spreading culinary herb — best contained in a pot.",
        "dimensions": [{"type": "Height", "min_value": 1, "max_value": 2, "unit": "feet"}],
        "cycle": "Perennial",
        "hardiness": {"min": "3", "max": "11"},
        "watering": "Frequent",
        "sunlight": ["part shade"],
        "soil": [],
        "flowers": True,
        "flowering_season": "Summer",
        "edible_fruit": False,
        "edible_leaf": True,
        "default_image": {},
    },
    {
        "id": 14,
        "common_name": "Rosemary",
        "scientific_name": ["Salvia rosmarinus"],
        "description": "Woody, drought-tolerant culinary herb, evergreen in mild climates.",
        "dimensions": [{"type": "Height", "min_value": 2, "max_value": 4, "unit": "feet"}],
        "cycle": "Perennial",
        "hardiness": {"min": "8", "max": "11"},
        "watering": "Minimum",
        "sunlight": ["full sun"],
        "soil": ["Sandy"],
        "flowers": True,
        "flowering_season": None,
        "edible_fruit": False,
        "edible_leaf": True,
        "default_image": {},
    },
    {
        "id": 15,
        "common_name": "Rhododendron",
        "scientific_name": ["Rhododendron catawbiense"],
        "description": "Broadleaf evergreen shrub with showy spring flower clusters.",
        "dimensions": [{"type": "Height", "min_value": 6, "max_value": 10, "unit": "feet"}],
        "cycle": "Perennial",
        "hardiness": {"min": "5", "max": "8"},
        "watering": "Average",
        "sunlight": ["full shade"],
        "soil": ["Acidic"],
        "flowers": True,
        "flowering_season": "Spring",
        "edible_fruit": False,
        "edible_leaf": False,
        "default_image": {},
    },
]
